"""
backend/services/local_standards.py

Real Indian Standards dataset for offline/local intelligence fallback.
Contains official BIS standards metadata for offline retrieval.
"""

LOCAL_STANDARDS = [
    {
        "is_number": "IS 3705:2024",
        "title": "Ball Point Pens and Refills — Specification",
        "category": "Stationery",
        "sub_category": "Pens & Writing Instruments",
        "product_keywords": ["ball point pen", "ball pen", "pen", "refill", "office stationery", "writing instrument"],
        "scope": "This standard specifies requirements and methods of sampling and test for general purpose ball point pens and refills suitable for office and general writing use.",
        "bis_status": "Active",
        "department": "PCD — Office Equipment and Stationery",
        "technical_committee": "PCD 25 — Office Equipment and Stationery",
        "type_of_standard": "Product Specification",
        "certification": {"status": "Voluntary", "mandatory": False},
        "normative_references": ["IS 3707:1986", "IS 10993:2005"],
        "test_methods": ["IS 3707:1986"],
        "amendments": [],
        "official_bis_url": "https://standards.bis.gov.in/website/know-your-standards/IS%203705:2024",
        "verification_source": "official_bis_cache",
        "data_source": "LOCAL_KNOWLEDGE_BASE"
    },
    {
        "is_number": "IS 10322 (Part 5/Sec 3):2012",
        "title": "Luminaires — Particular Requirements — Luminaires for Road and Street Lighting",
        "category": "Electrical & Electronics",
        "sub_category": "Lighting & Luminaires",
        "product_keywords": ["led street light", "street light", "led lamp", "road lighting", "outdoor luminaire", "ip66 street light"],
        "scope": "Specifies requirements for street lighting luminaires, including LED street lights for outdoor road lighting, ingress protection (IP66), electrical safety, and performance.",
        "bis_status": "Active",
        "department": "ETD — Electrotechnical",
        "technical_committee": "ETD 24 — Illumination Engineering",
        "type_of_standard": "Specification",
        "certification": {"status": "Mandatory (CRS)", "mandatory": True},
        "normative_references": ["IS 16101:2012", "IS 16102 (Part 1):2012", "IS 16103 (Part 1):2012"],
        "test_methods": ["IS 16106:2012"],
        "amendments": ["Amendment No. 1 (2018)"],
        "official_bis_url": "https://standards.bis.gov.in/website/know-your-standards/IS%2010322%20(Part%205/Sec%203):2012",
        "verification_source": "official_bis_cache",
        "data_source": "LOCAL_KNOWLEDGE_BASE"
    },
    {
        "is_number": "IS 16102 (Part 1):2012",
        "title": "Self-Ballasted LED Lamps for General Lighting Services — Part 1: Safety Requirements",
        "category": "Electrical & Electronics",
        "sub_category": "LED Lighting",
        "product_keywords": ["led lamp", "led bulb", "lighting", "electric lamp"],
        "scope": "Specifies safety and interchangeability requirements, together with the test methods and conditions required to show compliance of LED lamps.",
        "bis_status": "Active",
        "department": "ETD — Electrotechnical",
        "technical_committee": "ETD 24 — Illumination Engineering",
        "type_of_standard": "Safety Specification",
        "certification": {"status": "Mandatory (CRS)", "mandatory": True},
        "normative_references": ["IS 16101:2012"],
        "test_methods": ["IS 16106:2012"],
        "amendments": [],
        "official_bis_url": "https://standards.bis.gov.in/website/know-your-standards/IS%2016102%20(Part%201):2012",
        "verification_source": "official_bis_cache",
        "data_source": "LOCAL_KNOWLEDGE_BASE"
    },
    {
        "is_number": "IS 269:2015",
        "title": "Ordinary Portland Cement — Specification",
        "category": "Civil Engineering & Construction",
        "sub_category": "Cement & Building Materials",
        "product_keywords": ["cement", "opc", "ordinary portland cement", "opc 33", "opc 43", "opc 53", "concrete", "construction"],
        "scope": "Covers the manufacture and chemical and physical requirements for Ordinary Portland Cement of 33, 43 and 53 grades for building construction.",
        "bis_status": "Active",
        "department": "CED — Civil Engineering",
        "technical_committee": "CED 2 — Cement and Concrete",
        "type_of_standard": "Product Specification",
        "certification": {"status": "Mandatory (ISI Mark)", "mandatory": True},
        "normative_references": ["IS 4031 (Part 1):1988", "IS 4032:1985"],
        "test_methods": ["IS 4031 (Part 1):1988"],
        "amendments": ["Amendment No. 1 (2018)", "Amendment No. 2 (2020)"],
        "official_bis_url": "https://standards.bis.gov.in/website/know-your-standards/IS%20269:2015",
        "verification_source": "official_bis_cache",
        "data_source": "LOCAL_KNOWLEDGE_BASE"
    },
    {
        "is_number": "IS 1786:2008",
        "title": "High Strength Deformed Steel Bars and Wires for Concrete Reinforcement — Specification",
        "category": "Civil Engineering & Construction",
        "sub_category": "Steel & Rebar",
        "product_keywords": ["tmt bar", "steel bar", "deformed steel bar", "rebar", "fe 500", "fe 550", "reinforcement"],
        "scope": "Covers requirements for high strength deformed steel bars and wires for use as reinforcement in concrete structures.",
        "bis_status": "Active",
        "department": "CED — Civil Engineering",
        "technical_committee": "CED 54 — Concrete Reinforcement",
        "type_of_standard": "Specification",
        "certification": {"status": "Mandatory (ISI Mark)", "mandatory": True},
        "normative_references": ["IS 2062:2011", "IS 1608:2005"],
        "test_methods": ["IS 1608:2005"],
        "amendments": [],
        "official_bis_url": "https://standards.bis.gov.in/website/know-your-standards/IS%201786:2008",
        "verification_source": "official_bis_cache",
        "data_source": "LOCAL_KNOWLEDGE_BASE"
    },
    {
        "is_number": "IS 17803:2022",
        "title": "Stainless Steel Vacuum Insulated Water Bottles — Specification",
        "category": "Consumer Products",
        "sub_category": "Domestic Appliances",
        "product_keywords": ["water bottle", "stainless steel water bottle", "vacuum bottle", "flask"],
        "scope": "Specifies requirements for materials, dimensions, finish, insulation efficiency and thermal performance for stainless steel vacuum insulated water bottles.",
        "bis_status": "Active",
        "department": "PCD — Consumer Products",
        "technical_committee": "PCD 22 — Utensils and Cutlery",
        "type_of_standard": "Specification",
        "certification": {"status": "Mandatory (QCO)", "mandatory": True},
        "normative_references": ["IS 6911:2017"],
        "test_methods": ["IS 6911:2017"],
        "amendments": [],
        "official_bis_url": "https://standards.bis.gov.in/website/know-your-standards/IS%2017803:2022",
        "verification_source": "official_bis_cache",
        "data_source": "LOCAL_KNOWLEDGE_BASE"
    }
]
